//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casatoro.Datalayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedores
    {
        public Vendedores()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int Id { get; set; }
        public string NombreVendedor { get; set; }
        public string CedulaVendedor { get; set; }
    
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
