//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casatoro.Datalayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int Id { get; set; }
        public string ValorVenta { get; set; }
        public string NombreComprador { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public int VendedorId { get; set; }
        public int Vehiculos_Id { get; set; }
    
        public virtual Vehiculos Vehiculos { get; set; }
        public virtual Vendedores Vendedores { get; set; }
    }
}
