//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casatoro.Datalayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaVentas
    {
        public string Venta { get; set; }
        public string Comprador { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Vendedor { get; set; }
        public string Cedula { get; set; }
        public string Placa { get; set; }
        public string Color { get; set; }
        public string Marca { get; set; }
    }
}
